### ISSUE TITLE
Missing./train/train.py 

### ISSUE THREAD

**Issue by Tan-Hexiang** [oneal2000/MIND#1]
The ./train/train.py file in step 3 is not provided. Could you please provide the code for training?

**Comment by oneal2000** [comment]
We apologize for the confusion. The file you're looking for has been moved to a new location. You can find the train.py script under ./auto-labeled/train/train.py.

**Comment by Tan-Hexiang** [comment]
Get it! Thanks!

**Comment by Tan-Hexiang** [comment]
> We apologize for the confusion. The file you're looking for has been moved to a new location. You can find the train.py script under ./auto-labeled/train/train.py.

By the way. I have some questions about applying this pre-training method to other datasets: (1) The performance under the multiple-choice setting of TruthfulQA found in the appendix. Have you tried the performance in a free-form setting? (2) The sentences generated in the HaluEval-Dialog dataset are predetermined. How can we obtain the internal state of the model when it generates these sentences?

**Comment by oneal2000** [comment]
> > We apologize for the confusion. The file you're looking for has been moved to a new location. You can find the train.py script under ./auto-labeled/train/train.py.
> 
> By the way. I have some questions about applying this pre-training method to other datasets: (1) The performance under the multiple-choice setting of TruthfulQA found in the appendix. Have you tried the performance in a free-form setting? (2) The sentences generated in the HaluEval-Dialog dataset are predetermined. How can we obtain the internal state of the model when it generates these sentences?

In the context of Hallucination Detection Evaluation (HDE), Free Generation HDE involves a Language Learning Model (LLM) generating text, which is then manually annotated for hallucinations. The performance of a Hallucination Detection Model (HDM) is evaluated based on how well its assessments align with these human annotations.

On the other hand, Constrained Generation HDE uses annotated texts generated by an existing LLM to evaluate the HDM of another LLM. This involves feeding the existing texts into the new LLM and evaluating hallucinations based on these texts and the internal states of the new LLM.

As for your questions, both TruthfulQA and HaluEval-Dialog fall under the category of Constrained Generation. This is because they evaluate the correctness of existing texts. In this setting, the texts are input into the LLM, and hallucinations are detected based on the internal states of the LLM.

**Comment by Tan-Hexiang** [comment]
> > > We apologize for the confusion. The file you're looking for has been moved to a new location. You can find the train.py script under ./auto-labeled/train/train.py.
> > 
> > 
> > By the way. I have some questions about applying this pre-training method to other datasets: (1) The performance under the multiple-choice setting of TruthfulQA found in the appendix. Have you tried the performance in a free-form setting? (2) The sentences generated in the HaluEval-Dialog dataset are predetermined. How can we obtain the internal state of the model when it generates these sentences?
> 
> In the context of Hallucination Detection Evaluation (HDE), Free Generation HDE involves a Language Learning Model (LLM) generating text, which is then manually annotated for hallucinations. The performance of a Hallucination Detection Model (HDM) is evaluated based on how well its assessments align with these human annotations.
> 
> On the other hand, Constrained Generation HDE uses annotated texts generated by an existing LLM to evaluate the HDM of another LLM. This involves feeding the existing texts into the new LLM and evaluating hallucinations based on these texts and the internal states of the new LLM.
> 
> As for your questions, both TruthfulQA and HaluEval-Dialog fall under the category of Constrained Generation. This is because they evaluate the correctness of existing texts. In this setting, the texts are input into the LLM, and hallucinations are detected based on the internal states of the LLM.

Thank you very much for your detailed explanation！！！The practice of constrained generation seems to be similar to the approach described in the article "The Internal State of an LLM Knows When It's Lying", perhaps this is a common practice for the Probes method. However, would there be a certain difference in the internal state of the model between constrained generation and normal generation? Are they theoretically consistent? I have been trying to find relevant literature to confirm this, but have not found any.

**Comment by oneal2000** [comment]
You are welcome.

You are right, in the constrained generation, we are similar to "The Internal State of an LLM Knows When It's Lying." The only difference lies in that we use contextualized token embedding, and they use hidden activation.

To the best of my knowledge, there aren't any studies about the difference between hallucination detection of constrained generation and free generation.
