### ISSUE TITLE
May I ask how you loaded the large model?

### ISSUE THREAD

**Issue by zjj100-zjj** [oneal2000/MIND#3]
How do you load large models like llama7b, it is a pre-trained model downloaded from huggingface?

**Comment by oneal2000** [comment]
To load large pre-trained models like llama7b from Hugging Face, we first download the model to our local server. Taking llama7b as an example, you can download the entire model repository from the official Hugging Face page at https://huggingface.co/meta-llama/Llama-2-7b-chat/tree/main.

Once the model repository is downloaded locally, you can load the model based on the official documentation or sample code provided by Hugging Face. This typically involves using specific library functions to initialize and load the model from the local path.

**Comment by zjj100-zjj** [comment]
I have tried to succeed,thank you!
